# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: ['8','11']
        distribution: ['temurin','microsoft']
    name: Java ${{ matrix.java-version }} Build using ${{ matrix.distribution }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: ${{ matrix.distribution }}
    - name: Build with Ant
      run: ant -noinput -buildfile build-jar.xml jar
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: build/jar
